# Configuration for travis

language: r

sudo: false

warnings_are_errors: true

r-packages:
  - rmarkdown

r_check_args: --no-vignettes --no-build-vignettes

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
